version: '3.8'

services:
  rx-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rx-system
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5